import moment from 'moment';

export const emptyTodoArray = new Array<Todo>();

/* Act like we're getting date automatically from endpoint. */
export default [
  {
    id: 1,
    name: 'Groceries',
    desc: 'Apples, Lemons, Limes, Pear, & Grapes',
    dateCreated: moment(),
    exp: { has: true, date: moment().add(1, 'week') },
  },
  {
    id: 2,
    name: 'Do Chores',
    desc: 'Laundry, Dishes, Dust, & Trash',
    dateCreated: moment(),
    exp: { has: true, date: moment().add(1, 'week') },
  },
  {
    id: 3,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 4,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 5,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 6,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 7,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 8,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 9,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 10,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 11,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 12,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 13,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 14,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 15,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 16,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 17,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 18,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 19,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 20,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 21,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
  {
    id: 22,
    name: 'Send Project',
    desc: 'Send Todo Project to Verinovum!',
    dateCreated: moment('2020-04-15'),
    exp: { has: true, date: moment().add(4, 'days') },
  },
];
